### ISSUE TITLE
Depth example code for entire video?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [autonomousvision/unimatch#1]
Thanks for sharing this terrific work!

I see there's an example to generate a depth map for an image pair(not stereo), but is there example code that takes a video or full image sequence as input and outputs multiple depth maps so we can see the temporal consistency?   Thanks!

**Comment by haofeixu** [comment]
Thanks for your interest in our work!

Yes, we already provided the inference code for predicting depth maps of an image sequence, as shown in https://github.com/autonomousvision/unimatch/blob/master/scripts/gmdepth_demo.sh.
