### ISSUE TITLE
whether there is a disparity factor?

### ISSUE THREAD

**Issue by zhixiongzuo** [autonomousvision/unimatch#12]
Thanks for your excellent work, I use your code for stereo disparity estimate, but just find there is a gap betweent unimatch and disparity computing from sgbm as well as hitnet. In hitnet there is a param called png_disparity_factor, which can convert disparity to the same scale as sgbm. So is there a disparity factor too ? Thx.

**Comment by haofeixu** [comment]
No

**Comment by zhixiongzuo** [comment]
Thanks for your timely reply.Yeah, it just happened on  .png format disparity , I use .pfm format disparity and it  works now.
