### ISSUE TITLE
Meaning of the pretrained model

### ISSUE THREAD

**Issue by Steven-Xiong** [autonomousvision/unimatch#14]
Hello, thanks for your excellent work! I am just a little confused about the meaning of your pre-trained model. For instance, what is the meaning of the pretrained model 'gmstereo-scale2-regrefine3-resumeflowthings-sceneflow-f724fee6.pth'? Is it trained on both the flowthings dataset and sceneflow dataset, or trained on flowthings dataset and finetune on sceneflow dataset? How about the 'gmstereo-scale2-resumeflowthings-sceneflow-48020649.pth' pretrained model? Thank you.

**Comment by haofeixu** [comment]
Hi, thank you for your interest in our work.

As described in https://github.com/autonomousvision/unimatch/blob/master/MODEL_ZOO.md:

- The models are named as `model-dataset`.
- The `*-resumeflowthings-*` denotes that the models are trained with GMFlow model as initialization, where GMFlow is trained on Chairs and Things dataset for optical flow task.

Thus the model `gmstereo-scale2-regrefine3-resumeflowthings-sceneflow-f724fee6.pth` means using things pretrained GMFlow model as initilization, and then train for the stereo task on sceneflow.

Such naming applies to `gmstereo-scale2-resumeflowthings-sceneflow-48020649.pth` similarly.
