### ISSUE TITLE
How to generate pose files?

### ISSUE THREAD

**Issue by olegpokhilchenko** [autonomousvision/unimatch#15]
How to generate files for depth estimation:
demo/depth-scannet/intrinsic/intrinsic_depth.txt
demo/depth-scannet/pose/*

Where are any instructions? How to do this?

**Comment by haofeixu** [comment]
Hi, you could try colmap: https://github.com/fyusion/llff#1-recover-camera-poses

**Comment by olegpokhilchenko** [comment]
How about intrinsic_depth.txt?

**Comment by haofeixu** [comment]
Colmap can output both intrinsics and camera poses.

**Comment by neverstoplearn** [comment]
> How about intrinsic_depth.txt?

I follow the link and install COLORMAP to run python imgs2poses.py ../scenedir3/ and sussess. then I got sparse folder with have some *bin file and some *txt *db *npy file ,so how can I got the intrinsic and pose file after that ? have you fix that. I am new to this , look forward your answer.thanks.
