### ISSUE TITLE
Pretrained Model in Optical Flow Task

### ISSUE THREAD

**Issue by RickyYXY** [autonomousvision/unimatch#17]
I think when training unimatch begining at chairs(optical flow) dataset, we don't need a pretrained model.
But in your gmflow_scale2_regrefine6_train.sh, you add "resume" in the script, and the resume target gmflow-scale2-chairs-020cc9be.pth can't be found in model_zoo. Can you explain why?
Thks.

**Comment by haofeixu** [comment]
Sure the model can be trained from random initialization, but using a pretrained model can make the training converge faster. Sorry for missing the model `gmflow-scale2-chairs-020cc9be.pth` in our model zoo, it's available here: https://drive.google.com/file/d/1P3PrD636mQDQwMAK4Cv8ADoXUQ8QLMVD/view?usp=sharing

**Comment by RickyYXY** [comment]
OK, I get it! Thanks for your reply and code!
