### ISSUE TITLE
Intrisic parameters and poses?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [autonomousvision/unimatch#2]
Hi guys.  
Do I need to generate Intrinsic and pose files in some external software in order to use "main_depth.py" with my own images?  If so, can I use colmap for that?

**Comment by haofeixu** [comment]
Yes, we need the intrinsic and pose files for depth prediction, and they can be produced with colmap. You can refer to our demo files on Scannet (https://github.com/autonomousvision/unimatch/tree/master/demo/depth-scannet) for the file format.

**Comment by noobtoob4lyfe** [comment]
Thanks for the quick reply!  
 That link takes me to the same text files that inspired this question in the first place however.  How should I parse those mysterious numbers in those text files?   For example, is that a set of quaternions for the poses?  If so, what order are they in the following order "QW, QX, QY, QZ, TX, TY, TZ,"?   Does the intrinsic file contain the focal length, lens distortion, etc?   Is there a guide or legend for what these numbers mean?   Thanks!

**Comment by haofeixu** [comment]
Currently we are using ScanNet's data format for intrinsic and pose parameters, maybe taking a look at the data loading code (https://github.com/autonomousvision/unimatch/blob/master/dataloader/depth/datasets.py#L73-L80) would make it clearer. Hope it helps, thanks.
