### ISSUE TITLE
about multi-level feature extraction

### ISSUE THREAD

**Issue by Steven-Xiong** [autonomousvision/unimatch#20]
Hi, thanks for your great work. Is there possible ways to extract multi-level features in the optical flow estimation task? I notice there is a hyperparameter ' num_scales', but when I try to set it to 4, it seems it has correlation with the hyperparameter 'attn_splits_list', 'corr_radius_list' and 'prop_radius_list'. Could you show me how to adjust these three parameters if I would like to extract the 4 level upsample features? Thank you!

**Comment by haofeixu** [comment]
Hi, the 'attn_splits_list', 'corr_radius_list' and 'prop_radius_list' are lists where each element controls the corresponding paprameter of each scale. Thus if you use 4 scales, the length of these there parameters should also be 4.
