### ISSUE TITLE
Tartanair seems not available

### ISSUE THREAD

**Issue by StereoResearcher** [autonomousvision/unimatch#23]
Dear Professor:
The link "https://github.com/castacks/tartanair_tools/blob/master/download_training_zipfiles.txt" and other similar url seems not available in Tartanair project. 
"wget -c https://tartanair.blob.core.windows.net/tartanair-release1/*/*/depth_left.zip" returns an Error 

Warning: wildcards not supported in HTTP.
--2023-06-11 14:58:29--  https://tartanair.blob.core.windows.net/tartanair-release1/*/*/depth_left.zip
Resolving tartanair.blob.core.windows.net (tartanair.blob.core.windows.net)... 52.239.169.4
Connecting to tartanair.blob.core.windows.net (tartanair.blob.core.windows.net)|52.239.169.4|:443... connected.
HTTP request sent, awaiting response... 403 The specified account is disabled.
2023-06-11 14:58:30 ERROR 403: The specified account is disabled..

How could you solve this problem?

**Comment by haofeixu** [comment]
Hi, seems that this is an issue from tartanair side, you might want to contact the creator of this dataset for help, thanks.
