### ISSUE TITLE
How did you train the mixdata model for stereo task?

### ISSUE THREAD

**Issue by lynnezixuan** [autonomousvision/unimatch#3]
According to the name of the pretrained weight, my guess is:
1. Pretrained on Flowthings dataset  (resume the pretrained weight)
2. Mix all stereo datasets together
3. Train on the mixed dataset with resolution 320x640 first 
4. Fine-tune the model on the mixed dataset with the resolution 640x960 

Is this correct?

**Comment by haofeixu** [comment]
Yes, Scene Flow -> mixed data (320x640) -> mixed data (640x960). The model name tells everything :)

**Comment by EhrazImam** [comment]
Dear @haofeixu can you help me with detailed process for training mixed dataset

**Comment by EhrazImam** [comment]
Dear @haofeixu Can u help me to get more details have you mixed the entire data or just taken some data from every dataset. If so why you have trained it on both mixed data (320x640) -> mixed data (640x960)
