### ISSUE TITLE
About weights

### ISSUE THREAD

**Issue by hyw-dev** [autonomousvision/unimatch#31]
Hello, may I ask if you can provide the sintel-gmflow-scale2-regrefine6.pth

**Comment by haofeixu** [comment]
Hi, here it is: https://mailustceducn-my.sharepoint.com/:u:/g/personal/xhf_mail_ustc_edu_cn/EVFLAlQzg_BHqei2vEaHlwIBhh0IBsPViM2df8rupjAjAw?e=dLNqI4

**Comment by hyw-dev** [comment]
Thanks for your weight.
