### ISSUE TITLE
Resetting hidden state during refinement

### ISSUE THREAD

**Issue by qzed** [autonomousvision/unimatch#37]
It looks looks you're resetting the hidden-state during each RAFT-based refinement step. Is this done on purpose?

https://github.com/autonomousvision/unimatch/blob/0dfa3616d89790ac3bac3810dcdedf691b40dfdd/unimatch/unimatch.py#L317-L322

**Comment by haofeixu** [comment]
No, just based on intuitions :)

**Comment by qzed** [comment]
Thanks! Feel free to close this issue (although I think it could be nice to have a comparison whether this leads to some improvement).
