### ISSUE TITLE
Running in Windows?

### ISSUE THREAD

**Issue by vitacon** [autonomousvision/unimatch#38]
Did anyone try to run UniMatch in Windows?
I modified conda_environment.yml to include more channels (conda-forge) and removed some required versions. It solved some of the problems but it still miss 18 packages which seems to be available only for other OS. 
Is there an easy way around it?

```
ResolvePackageNotFound: (sorted =)
  - _openmp_mutex=5.1
  - dbus
  - gmp
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - ld_impl_linux-64=2.38
  - libgcc-ng
  - libgfortran5
  - libgfortran-ng
  - libgomp=11.2.0
  - libidn2=2.3.2
  - libstdcxx-ng
  - libtasn1=4.16.0
  - libunistring
  - libuuid=1.41.5
  - ncurses
  - nettle=3.7.3
  - readline=8.2
```

**Comment by haofeixu** [comment]
Hi I haven't tested in Windows, probably you can try to install with pip https://github.com/autonomousvision/unimatch/blob/master/pip_install.sh if the conda_environment.yml doesn't work.
