### ISSUE TITLE
Decoding RGB Optical Flow for Motion Information Extraction in Video Action Recognition

### ISSUE THREAD

**Issue by seekerhuang** [autonomousvision/unimatch#41]
Hi.

After performing inference, the obtained optical flow is an RGB image with three channels. If my objective is to utilize this RGB optical flow image for video action recognition and I need to decode it back to its original form (rescaled back to its original range) to extract motion information, could you kindly guide me on how to accomplish this?

Thank you very much!

**Comment by haofeixu** [comment]
Hi, you can use `--save_flo_flow` to save raw flow prediction as .flo file.

**Comment by jokingww** [comment]
> Hi, you can use `--save_flo_flow` to save raw flow prediction as .flo file.

Hello, could you please tell how to resize .flo file in correct way. I just try np.size but the result is confused.

**Comment by haofeixu** [comment]
Hi you should resize the numpy or torch flow arrays instead of the .flo flow file.
