### ISSUE TITLE
What is the best resolution for inferencing optical flow?

### ISSUE THREAD

**Issue by CJCHEN1230** [autonomousvision/unimatch#42]
Thanks for sharing such a Nice Work!!!
I use "gmflow-scale2-regrefine6-mixdata-train320x576-4e7b215d.pth" for inferencing the optical flow. My purpose is to use the optical flow as my ground truth for single image depth estimation. However, I found that different resolution will make huge difference. 
Input 
![image](https://github.com/autonomousvision/unimatch/assets/22461372/42eb2872-0908-4810-8f81-cc96385046ce)

resolution 1888*1015
![image](https://github.com/autonomousvision/unimatch/assets/22461372/4bff82be-513c-48a3-b9a4-a10b611baab2)

half resolution 944*507
![image](https://github.com/autonomousvision/unimatch/assets/22461372/6e2b6856-4a98-476b-8b3e-de5ce533947e)

1/4 resolution  472*253
![image](https://github.com/autonomousvision/unimatch/assets/22461372/281560b9-cbc0-4add-9ffe-fef799648764)

1/8  236*126
![image](https://github.com/autonomousvision/unimatch/assets/22461372/60415a53-5d88-4dc7-9ddb-5bf4ea74b549)

Does that make sense?  I tried the stereo matching, but I didn't encounter the same situation. Maybe the best resolution for inferencing optical flow is as close as the training size? Or how do I get the best quality of optical flow with large resolution?

**Comment by haofeixu** [comment]
Hi, this could be expected since the model is not very robust to inference resolution currently. I think the models should be able to handle higher resolutions like ~512x1024, but even higher might be problematic. In practice you might need to tune the inference size to get the optimal performance for your data.

**Comment by CJCHEN1230** [comment]
Thanks for your response. I'm a newbie in this field. I recently find many research generate depth label by optical flow. I never see any mention about this kind of situation.  In tradition, is optical flow model usually  sensitive to resolution?

**Comment by haofeixu** [comment]
Yes, this is a common issue.

**Comment by CJCHEN1230** [comment]
Thanks!
