### ISSUE TITLE
Request for new weights

### ISSUE THREAD

**Issue by hyw-dev** [autonomousvision/unimatch#44]
The gmflow/unimatch sintel model performs very well in 3D animation. Btw, the [Spring optical flow](https://spring-benchmark.org/) dataset was recently released at CVPR2023. Do you have any plans to finetune or train a new model on Spring?

**Comment by haofeixu** [comment]
Hi currently we didn't have a plan to train our model on Spring, you are very welcome to finetune to it with our pretrained model.
