### ISSUE TITLE
gmstereo_scale1_train.sh

### ISSUE THREAD

**Issue by Wdy1234566** [autonomousvision/unimatch#45]
"Hello, while executing gmstereo_scale1_train.sh, I switched the training set to kitti15mix and used only kitti15 for the evaluation set. However, after 100,000 iterations, the results were not very good. I did not modify any parameters. Could this be the reason for the suboptimal performance? I look forward to your reply and guidance. Thank you."

**Comment by haofeixu** [comment]
Could you please give more details e.g. training log?
