### ISSUE TITLE
unimatch.py line 257

### ISSUE THREAD

**Issue by HaiLiExp** [autonomousvision/unimatch#47]
Hello

I wonder whether the min_depth and max_depth should be reversed because "min_depth" here is the inverse depth.

depth_up_pad = self.upsample_flow(depth_pad, feature0,
                                                          is_depth=True).clamp(min=min_depth, max=max_depth)

BR
Hai

**Comment by haofeixu** [comment]
Hi, it's inverse depth here, and it's converted to depth at https://github.com/autonomousvision/unimatch/blob/master/unimatch/unimatch.py#L360-L363
