### ISSUE TITLE
[GMflow] What do the ’train_dataset ‘ equation coefficients mean when stage=sintel？

### ISSUE THREAD

**Issue by zhengqianisme** [autonomousvision/unimatch#48]
[GMflow] I see that if stage=sintel, train_dataset = 100 * sintel_clean + 100 * sintel_final + 200 * kitti + 5 * hd1k + things. '100,200,5' , What do these coefficients mean?

**Comment by haofeixu** [comment]
Hi, they are the number of replicates of different datasets since each dataset has different number of samples.
