### ISSUE TITLE
How to optimize with TorchScript and TensorRT

### ISSUE THREAD

**Issue by Shahrullo** [autonomousvision/unimatch#5]
Thanks for sharing the model and weights. It's working efficiently. Inference accuracy and speed are good. However, I want to deploy it on Jetson Orin, it's working with good accuracy, however FPS is not so good. So I want to optimize the pretraineed model with TorchScript or TensorRT. Is there any work going on or guideline how to deploy the **"unimatch"** for edge devices?

**Comment by haofeixu** [comment]
Thanks for your interest in our work. Unfortunately we are not working on delopying for edge devices currently and we have also no plan to do this in the future. For speeding up, maybe you can try to optimize our implementation or use quantization or half precision etc, but I didn't have too much experience on TorchScript and TensorRT thus I am not able to provide very detailed guidelines to achieve this. Anyway, this is indeed a valuable direction for practical applications and I would be very happy to hear more about your work on this in the future :)

**Comment by Shahrullo** [comment]
Thank you very much for your detailed response. Indeed, After optimizing and putting on practical application, I will definitely let you know!

**Comment by GhaCH** [comment]
Hi @haofeixu, I'm facing the same challenge as you and wanted to ask if you found anything that might help optimize the model with TensorRT. Thank you.
