### ISSUE TITLE
tartan air dataset

### ISSUE THREAD

**Issue by ylab604** [autonomousvision/unimatch#52]
I knowed that tartan air dataset's depth map is not disparity but,  there is no changing disparity code to depth in the dataset build code.
 
Would you plz what is the right sense?

**Comment by haofeixu** [comment]
Hi, the tartan air dataset is only used for stereo disparity estimation in our experiments and it's not used for the depth task.

**Comment by ylab604** [comment]
> Hi, the tartan air dataset is only used for stereo disparity estimation in our experiments and it's not used for the depth task.

Thank you for your kindness
I understand that the Tartan-Air dataset provides GT (ground truth) values as left_depth.npy. I believe these are depth values, but am I misunderstanding something? 
https://github.com/castacks/tartanair_tools/blob/master/data_type.md#depth-image
<img width="1063" alt="image" src="https://github.com/autonomousvision/unimatch/assets/99255566/f6f8f0e2-61f3-45a2-8750-b8d25a13bc32">


If I'm mistaken, I would appreciate your correction. As always, I send my admiration for your efforts.

**Comment by vislero** [comment]
Hi @haofeixu 

Hello, In your 'dataset.py' code, I noticed that for common datasets like KITTI, disparity images are loaded as GT. However, for datasets like Tartan Air, depth maps instead like belows. 

https://github.com/autonomousvision/unimatch/blob/0dfa3616d89790ac3bac3810dcdedf691b40dfdd/dataloader/stereo/datasets.py#L546

https://github.com/autonomousvision/unimatch/blob/0dfa3616d89790ac3bac3810dcdedf691b40dfdd/dataloader/stereo/datasets.py#L621

Given that these two types(disparity <-> depth) of data represent different things, I'm concerned this difference could potentially impact the learning process. Could you clarify if this is the case and if the variation in data representation between datasets is intended to influence the training outcomes?

**Comment by haofeixu** [comment]
Hi @ylab604 @vislero ,
There is a `is_tartanair` flag in the TartanAir definition https://github.com/autonomousvision/unimatch/blob/master/dataloader/stereo/datasets.py#L542
and its corresponding data loader will be used https://github.com/autonomousvision/unimatch/blob/master/utils/file_io.py#L38-L39

**Comment by ylab604** [comment]
@haofeixu Thank you sir!
