### ISSUE TITLE
Question about Real Distance Calculation from Disparity Map

### ISSUE THREAD

**Issue by ArmanFz** [autonomousvision/unimatch#58]
Hello, I have a question regarding the calculation of real distance from a disparity map using the formula $D = b*f/d$
- $D$ is Distance of the point in real world
- $b$ is the baseline (the distance between my cameras) 
- $f$ is the focal length of the camera 
- $d$ is the disparity

Should I use centimeters or meters for these metrics? Specifically, should the baseline ($b$) and focal length ($f$) be in centimeters or meters, or does it not matter as long as they are in the same unit?  Thank you!

**Comment by haofeixu** [comment]
Hi typically the focal length is expressed in pixels, and disparity is also in pixels. The unit of b*f/d is consistent with the baseline b (i.e., you get meters if you provide the baseline with unit meters).
