### ISSUE TITLE
Training for depth on my own custom dataset

### ISSUE THREAD

**Issue by YacineDeghaies** [autonomousvision/unimatch#62]
Hi, 
I'd like to train the model to estimate depth using my own dataset that is made up of only RGB images and their ground truth depth maps. Can you please give me any hints on how to tackle this ? Thank you
 
I thought modifying the DemonDataset class..

**Comment by haofeixu** [comment]
Hi, you will need to write the code to load the images, intrinsic & extrinsic matrices, and the corresponding grouth truth. Yes you can modify the `__init__` func in the DemonDataset class.

**Comment by haofeixu** [comment]
Yes, we assume intrinsic and extrinsic parameters are known. However, if your image resolution is 1080x1920, our model so far is not able to handle such high-resolution images very efficiently.

**Comment by YacineDeghaies** [comment]
Thank you for helping !
