### ISSUE TITLE
Computing pose.txt

### ISSUE THREAD

**Issue by Yijia-Xiao** [autonomousvision/unimatch#7]
Hi,

I am using this work to finetune on some depth images and make prediction.

However, I encountered some difficulty when trying to compute pose.txt for images. In your code, it seems that you are using colmap to get the pose.txt file for each image. I referred to colmap but couldn't figure out how to do that ([issue](https://github.com/colmap/colmap/issues/1594) in colmap). Could you provide some details/scripts on that?

BTW, I wonder if there will be an approach to directly predict depth from monocular images? It seems that current inference code needs consecutive images from one scene [evaluate_depth.py#L338](https://github.com/autonomousvision/unimatch/blob/master/evaluate_depth.py#L338).

Thank you!

**Comment by haofeixu** [comment]
Besides the instruction you mentioned in colmap repo, you can also try this one: https://github.com/fyusion/llff#1-recover-camera-poses

Our method only supports two or more posed images as input for depth prediction. If you are looking for single image depth estimation methods, you might want to try https://github.com/isl-org/DPT

**Comment by Yijia-Xiao** [comment]
Hi @haofeixu,
Thank you for your detailed reply:thumbsup:. I will check it out.

**Comment by Yijia-Xiao** [comment]
Hi @haofeixu ,

I tried https://github.com/fyusion/llff#1-recover-camera-poses, but got error message `ERROR: failed to create sparse model`.
I am wondering if it would be convenient to share the `colmap` scripts you used to extract the pose for https://github.com/autonomousvision/unimatch/tree/master/demo/depth-scannet (from color images and intrinsic to pose).

**Comment by neverstoplearn** [comment]
> Hi @haofeixu ,
> 
> I tried https://github.com/fyusion/llff#1-recover-camera-poses, but got error message `ERROR: failed to create sparse model`. I am wondering if it would be convenient to share the `colmap/llff` scripts you used to extract the pose for https://github.com/autonomousvision/unimatch/tree/master/demo/depth-scannet (from color images and intrinsic to pose).

have you solve that,I meet save error.
