### ISSUE TITLE
Depth estimation from images without any pose information

### ISSUE THREAD

**Issue by spiegelball** [autonomousvision/unimatch#8]
Very nice results! Is it possible to generate depth information from an image sequence which has no pose information at all?

**Comment by haofeixu** [comment]
Unfortunately not for our method, we need the pose information to model the geometry constraints for feature matching.

**Comment by renwuli** [comment]
Hi @haofeixu, with respect to the demo of depth estimation, using the same settings as the colab notebook, after adding some noise to the rotation part of pose while keeping the translation part the same, I found the depth quality drops a lot. Similarly, after adding some noise to the translation part of pose while keeping the rotation part the same, the depth quality drops a lot as well. Seems like the depth estimation head is not robust to pose. Any ideas to handle this?

**Comment by FreakTheMighty** [comment]
@spiegelball @haofeixu are poses used when estimating flow? It didn't seem to me that they were. If not, then it would seem to me this could be done in two stages

- Estimate the flow
- Estimate camera pose from intrinsics + features matches
- Estimate depth
