### ISSUE TITLE
Colmap for pose computing

### ISSUE THREAD

**Issue by Yijia-Xiao** [autonomousvision/unimatch#9]
Hi,

I tried https://github.com/fyusion/llff#1-recover-camera-poses, and got `poses_bounds.npy` for each pair of frames from video. There are 17 pose parameters for each image, but it seems that there are 4 * 4 parameters in each `pose.txt` file.

I would appreciate it if you could provide the scripts used to extract the pose from `poses_bounds.npy`.

- Computation of 17 pose parameters.
![unimatch](https://user-images.githubusercontent.com/48253104/205557051-b622aa21-010d-4e0e-ab40-e030f7c38a32.png)

- Loading of pose.txt in unimatch
![load](https://user-images.githubusercontent.com/48253104/205557164-3eee4999-af01-4153-9b9e-7a69e24679cd.png)

**Comment by haofeixu** [comment]
Resolved via email.

**Comment by noobtoob4lyfe** [comment]
Can you share the resolution to this?  I too would like to know how to use colmap for poses

**Comment by noobtoob4lyfe** [comment]
Anyone there?

**Comment by spicy-dog** [comment]
@Yijia-Xiao Hi, can you share the resolution to this?
